services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: libras
    ports: ["5432:5432"]
    volumes: [db-data:/var/lib/postgresql/data]
volumes: { db-data: {} }
